name: Check samples

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  samples:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sample: ["slack-samples/deno-hello-world", "slack-samples/deno-message-translator"]

    steps:
      - name: Checkout the sdk
        uses: actions/checkout@v3
        with:
          path: ./deno-slack-sdk
      - name: Checkout the ${{ matrix.sample }} sample
        uses: actions/checkout@v3
        with:
          repository: ${{ matrix.sample }}
          path: ./sample
      
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Edit sdk dependency to use checkout version
        run: sed -r -i 's/https:\/\/deno\.land\/x\/deno_slack_sdk@[0-9]+\.[0-9]+\.[0-9]+\//\.\.\/deno-slack-sdk\/src\//p' sample/import_map.json
      
      - name: print ls
        working-directory: ./sample
        run: ls

      - name: deno check
        working-directory: ./sample
        run: deno check -r --all manifest.ts

      - name: deno check
        working-directory: ./sample
        run: deno check -r --all *.ts **/*.ts

