name: Check samples

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  samples:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sample: ["slack-samples/deno-hello-world"]

    steps:
      - uses: actions/checkout@v3
        with:
          path: deno-slack-sdk
      - uses: actions/checkout@v3
        with:
          repository: ${{ matrix.sample }}
          path: sample
      - name: Set up sample ${{ matrix.sample }}
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Run tests
        run: find . -type d

